### ISSUE TITLE
DateSpan .fromNow and server-side rendering

### ISSUE THREAD

**Issue by Soreine** [GitbookIO/styleguide#15]
The DateSpan component is likely to trash the whole server-rendered DOM when React mounts. Consider the following scenario:
- A page includes a DateSpan (`fromNow`) of a few seconds ago
- The DOM is rendered on the server-side, the DateSpan renders `2 seconds ago`
- The client receive the served HTML, React mounts, and sees that DateSpan now renders `3 seconds ago`.
- -> The whole DOM is trashed because it doesn't match.

**Comment by AaronO** [comment]
@Soreine Yep, that happened to me a few times. The obvious fix would be to include the "now" timestamp in the `JSON` payload rather than calling `Date.now()` in the rendering code.

Thus the client starts off with the same timestamp as the server but can then update it with a `setTimeout` / `setInterval` loop.
